title: "Razeen Hussain"
author: "Razeen"
description: " "
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: true        # show a sidebar instead of the usual header
minimal: true             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {title: "Home", sidebaricon: home, file: "index.md"}
  - {title: "Education", sidebaricon: landmark, file: "education.md"}
  - {title: "Experience", sidebaricon: building, file: "experience.md"}
  - {title: "Research", sidebaricon: folder, file: "research.md"}
  - {title: "Publications", sidebaricon: print, file: "publications.md"}
  - {title: "Academic", sidebaricon: book, file: "academic.md"}
  - {title: "Teaching", sidebaricon: clipboard, file: "teaching.md"}
  - {title: "Events", sidebaricon: map, file: "events.md"}
  - {title: "CV", sidebaricon: file, url: "assets/razeen.pdf"}
  - {title: "Lab", sidebaricon: tag, url: "https://pilab.unige.it"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:razeenhussain@hotmail.com"}
  - {title: Linkedin, icon: linkedin, url: "https://www.linkedin.com/in/razeenhussain"}
  - {title: Google Scholar, icon: bookmark, url: "https://scholar.google.com/citations?user=MRIAQdAAAAAJ"}
  - {title: ResearchGate, icon: researchgate, url: "https://www.researchgate.net/profile/Razeen-Hussain"}
  - {title: GitHub, icon: github, url: "https://github.com/RazeenHussain"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
